repmgr_db: "repmgr"
repmgr_user: "repmgr"
repmgr_password: "repmgr"
repmgr_config_path: "/etc/repmgr/12/repmgr.conf"
repmgr_service_name: "postgresql"
network_subnet_master: "{{ master_private_ip }}/24"
network_subnet_worker1: "{{ worker1_private_ip }}/24"
network_subnet_worker2: "{{ worker2_private_ip }}/24"
