- name: Create pglogical user and database
  hosts: master_nodes
  become: yes
  pre_tasks:
    - name: Create pglogical database
      community.postgresql.postgresql_db:
        name: pglogical_db
        state: present
      become_user: postgres
      register: db_creation

    - name: Debug database creation output
      debug:
        var: db_creation

    - name: Check if pglogical_db exists
      community.postgresql.postgresql_query:
        db: postgres
        query: "SELECT datname FROM pg_database WHERE datname = 'pglogical_db';"
      become_user: postgres
      register: db_check

    - name: Debug database existence check
      debug:
        var: db_check
