- name: Ensure pglogical database exists
  hosts: master_nodes
  become: yes
  tasks:
    - name: Check if pglogical_db exists
      community.postgresql.postgresql_query:
        db: postgres
        query: "SELECT 1 FROM pg_database WHERE datname = 'pglogical_db';"
      become_user: postgres
      register: db_check
      failed_when: db_check.rowcount > 1

    - name: Create pglogical database if not exists
      community.postgresql.postgresql_db:
        name: pglogical_db
        state: present
      become_user: postgres
      when: db_check.rowcount == 0

    - name: Grant privileges on pglogical database
      community.postgresql.postgresql_privs:
        db: pglogical_db
        privs: "ALL"
        type: database
        roles: pglogical_user
        state: present
      become_user: postgres
