- name: Subscribe master to other nodes
  hosts: master_nodes
  become: yes
  tasks:
    - name: Subscribe to Worker 1 node
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: |
          SELECT pglogical.create_subscription(
            subscription_name := 'subscription_{{ ansible_hostname | lower }}_to_worker1',
            provider_dsn := 'host={{ worker1_private_ip }} port=6588 dbname=pglogical_db user=pglogical_user password=securepassword'
          );
        login_port: 6588
      become_user: postgres

    - name: Subscribe to Worker 2 node
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: |
          SELECT pglogical.create_subscription(
            subscription_name := 'subscription_{{ ansible_hostname | lower }}_to_worker2',
            provider_dsn := 'host={{ worker2_private_ip }} port=6588 dbname=pglogical_db user=pglogical_user password=securepassword'
          );
        login_port: 6588
      become_user: postgres