---
- name: Setup pglogical on all PostgreSQL nodes
  hosts: all_nodes
  become: yes

  tasks:
    - name: Ensure pglogical is in shared_preload_libraries
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?shared_preload_libraries\s*='
        line: "shared_preload_libraries = 'pglogical'"
        backup: yes

    - name: Restart PostgreSQL to apply changes
      systemd:
        name: postgresql
        state: restarted

    - name: Create pglogical extension in pglogical_db
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: "CREATE EXTENSION IF NOT EXISTS pglogical;"
      become_user: postgres
