- name: Create pglogical Node on Standby
  hosts: worker_nodes
  become: yes
  tasks:

    - name: Create pglogical database
      community.postgresql.postgresql_db:
        name: pglogical_db
        state: present
        login_port: 6588
      become_user: postgres

    - name: Ensure pglogical database exists
      community.postgresql.postgresql_query:
        db: postgres
        query: "SELECT 1 FROM pg_database WHERE datname = 'pglogical_db';"
        login_port: 6588
      become_user: postgres
      register: db_check
      failed_when: db_check.rowcount == 0

    - name: Create pglogical user
      community.postgresql.postgresql_user:
        name: pglogical_user
        password: "securepassword"
        role_attr_flags: "LOGIN,REPLICATION"
        state: present
        login_port: 6588
      become_user: postgres

    - name: Ensure database is ready before granting privileges
      pause:
        seconds: 5  # Ensure the database is fully available

    - name: Create pglogical extension
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: "CREATE EXTENSION IF NOT EXISTS pglogical;"
        login_port: 6588
      become_user: postgres

    - name: Grant full privileges on pglogical database
      community.postgresql.postgresql_privs:
        db: pglogical_db
        privs: "ALL"
        type: database
        roles: pglogical_user
        state: present
        login_port: 6588
      become_user: postgres

    - name: Grant USAGE on pglogical schema to pglogical_user
      community.postgresql.postgresql_privs:
        db: pglogical_db
        privs: "USAGE"
        type: schema
        roles: pglogical_user
        objs: pglogical
        login_port: 6588
        state: present
      become_user: postgres

    - name: Grant SELECT on all tables in public schema to pglogical_user
      community.postgresql.postgresql_privs:
        db: pglogical_db
        privs: "SELECT"
        type: table
        schema: public
        roles: pglogical_user
        objs: "ALL_IN_SCHEMA"
        login_port: 6588
        state: present
      become_user: postgres

    - name: Add standby node to pglogical
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: |
          SELECT pglogical.create_node(
            node_name := '{{ ansible_hostname }}',
            dsn := 'host={{ worker_private_ip }} port=6588 dbname=pglogical_db user=pglogical_user password=securepassword'
          );
        login_port: 6588
      become_user: postgres
      ignore_errors: yes

    - name: Restart PostgreSQL before subscriptions
      shell: "systemctl restart postgresql"
      become: yes

    - name: Wait for PostgreSQL to start
      pause:
        seconds: 10

    - name: Subscribe to primary node
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: |
          SELECT pglogical.create_subscription(
            subscription_name := 'subscription_{{ ansible_hostname | lower }}',
            provider_dsn := 'host={{ master_private_ip }} port=6588 dbname=pglogical_db user=pglogical_user password=securepassword'
          );
        login_port: 6588
      become_user: postgres
      register: result
      retries: 3
      delay: 5
      until: result is not failed

    - name: Subscribe to other standby nodes
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: |
          SELECT pglogical.create_subscription(
            subscription_name := 'subscription_{{ ansible_hostname | lower }}_other',
            provider_dsn := 'host={{ other_worker_private_ip }} port=6588 dbname=pglogical_db user=pglogical_user password=securepassword'
          );
        login_port: 6588
      become_user: postgres
      retries: 3
      delay: 5
      register: result
      until: result is not failed
