- name: Create pglogical user and database
  hosts: master_nodes
  become: yes
  pre_tasks:
    - name: Create pglogical database
      shell: sudo -u postgres psql -c "CREATE DATABASE pglogical_db;"
      
    - name: Create pglogical user
      community.postgresql.postgresql_user:
        name: pglogical_user
        password: "securepassword"
        role_attr_flags: "LOGIN,REPLICATION"
        state: present
      become_user: postgres
    - name: Grant privileges on pglogical database
      community.postgresql.postgresql_privs:
        db: pglogical_db
        objs: ALL
        privs: "ALL"
        type: database
        roles: pglogical_user
        state: present
      become_user: postgres
      
    - name: Create pglogical extension
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: "CREATE EXTENSION IF NOT EXISTS pglogical;"
      become_user: postgres
      
  tasks:
    - name: Add primary node to pglogical
      community.postgresql.postgresql_query:
        db: pglogical_db
        query: |
          SELECT pglogical.create_node(
            node_name := '{{ ansible_hostname }}',
            dsn := 'host={{ ansible_host }} dbname=pglogical_db user=pglogical_user password=postgres'
          );
      become_user: postgres
