---
- name: Config Kuberenets on Master
  hosts: master
  become: yes
  become_user: root
  tasks:
    - name: Pull kubeadm configuration images
      command: kubeadm config images pull

    - name: Initialize the Kubernetes cluster
      shell: |
        kubeadm init --apiserver-advertise-address={{ master_private_ip }} --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_output

    - name: Display kubeadm initialization output
      debug:
        msg: "{{ kubeadm_init_output.stdout }}"

    - name: Store Kubernetes initialization output to file
      copy:
        content: "{{ kubeadm_init_output.stdout }}"
        dest: /tmp/kubeadm_join_cmd
      become: true
      delegate_to: localhost
    
    - name: Ensure .kube directory exists
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy kubeconfig as root
      command: cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
      become: yes  # Run as root

    - name: Set correct permissions
      file:
        path: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      become: yes  # Run as root


    - name: Apply Flannel CNI
      shell: KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply --validate=false -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentat>
      become: yes
      become_user: "{{ ansible_user }}"
