---
- name: Config Kuberenets on Workers
  hosts: worker1,worker2
  become: yes
  become_user: root
  tasks:
    - name: Copy join-command file to worker nodes
      copy:
        src: /tmp/kubeadm_join_cmd
        dest: /tmp/kubeadm_join_cmd
        mode: '0755'

    - name: Join the worker nodes to the Kubernetes cluster
      shell: /tmp/kubeadm_join_cmd
      become: yes
