---
- name: Config Kuberenets on Master
  hosts: master
  become: yes
  become_user: root
  tasks:
    - name: Pull kubeadm configuration images
      command: kubeadm config images pull

    - name: Initialize the Kubernetes cluster
      shell: |
        kubeadm init --apiserver-advertise-address={{ master_private_ip }} --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_output

    - name: Display kubeadm initialization output
      debug:
        msg: "{{ kubeadm_init_output.stdout }}"

    - name: Store Kubernetes initialization output to file
      copy:
        content: "{{ kubeadm_init_output.stdout }}"
        dest: /tmp/kubeadm_join_cmd
      become: true
      delegate_to: localhost

    - name: Set up kubeconfig for non-root user
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      when: ansible_user != 'root'

    - name: Apply Flannel CNI
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
