---
- name: Config Kuberenets on Workers
  hosts: worker1,worker2
  become: yes
  become_user: root
  tasks:
    - name: Copy join-command file to worker nodes
      copy:
        src: /tmp/kubeadm_join_cmd
        dest: /tmp/kubeadm_join_cmd
        mode: '0755'

    - name: Read the last two lines of the kubeadm join command
      shell: tail -n 2 /tmp/kubeadm_join_cmd | tr -d '\\\n'
      register: kubeadm_join_cmd_raw
      delegate_to: localhost  # Runs on Ansible control node

    - name: Trim whitespace and join lines into a single command
      set_fact:
        kubeadm_join_cmd: "{{ kubeadm_join_cmd_raw.stdout_lines | join(' ') }}"

    - name: Debug the extracted join command
      debug:
        msg: "{{ kubeadm_join_cmd }}"

    - name: Reset Kubernetes on worker nodes before joining
      shell: kubeadm reset -f
      become: yes
      ignore_errors: yes  # Ignore errors if the node is fresh

    - name: Join the worker nodes to the Kubernetes cluster
      shell: "{{ kubeadm_join_cmd }}"
      become: yes
