---
- name: Check if repmgr is installed
  shell: dpkg -l | grep repmgr
  register: repmgr_installed
  ignore_errors: true

- name: Install prerequisites if repmgr is not installed
  apt:
    name:
      - flex
      - libedit-dev
      - libkrb5-dev
      - libpam0g-dev
      - libreadline-dev
      - libselinux1-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - build-essential
      - postgresql-server-dev-14
      - liblz4-dev 
      - zlib1g-dev
    state: present
  when: repmgr_installed.rc != 0

- name: Download repmgr source code
  get_url:
    url: https://repmgr.org/download/repmgr-5.3.3.tar.gz
    dest: /tmp/repmgr-5.3.3.tar.gz
  when: repmgr_installed.rc != 0

- name: Extract repmgr source code
  unarchive:
    src: /tmp/repmgr-5.3.3.tar.gz
    dest: /tmp/
    remote_src: yes
  when: repmgr_installed.rc != 0

- name: Configure and install repmgr
  shell: |
    cd /tmp/repmgr-5.3.3 &&
    ./configure &&
    make &&
    make install
  when: repmgr_installed.rc != 0

- name: Check repmgr service status
  shell: systemctl status repmgr
  register: repmgr_status
  ignore_errors: true

- name: Debug repmgr service status
  debug:
    msg: "Repmgr service status: {{ repmgr_status.stdout }}"
