---
- name: Check if repmgr is installed
  shell: dpkg -l | grep repmgr
  register: repmgr_installed
  ignore_errors: true

- name: Add 2ndQuadrant repository
  shell: curl https://dl.2ndquadrant.com/default/release/get/deb | bash
  args:
    creates: /etc/apt/sources.list.d/2ndquadrant.list
# when: repmgr_installed.rc != 0

- name: Update apt cache
  apt:
    update_cache: yes
  when: repmgr_installed.rc != 0

- name: Install repmgr for PostgreSQL 12
  apt:
    name: postgresql-12-repmgr
    state: present
  when: repmgr_installed.rc != 0
