- name: Deploy PostgreSQL HA with Patroni using Kubernetes etcd
  hosts: postgresql_nodes
  become: yes
  vars:
    patroni_config_path: "/etc/patroni.yml"
    pg_data_dir: "/var/lib/postgresql/14/main"
    etcd_url: "http://etcd-service.kube-system.svc.cluster.local:2379"
    cluster_name: "pg-cluster"
    replication_user: "replicator"
    replication_password: "replica_pass"
    postgresql_admin_user: "postgres"
    postgresql_admin_password: "secure_password"

  tasks:
    - name: Create Patroni configuration file
      template:
        src: patroni.yml.j2
        dest: "{{ patroni_config_path }}"
        owner: postgres
        group: postgres
        mode: 0644

    - name: Enable and restart Patroni service
      systemd:
        name: patroni
        enabled: yes
        state: restarted

    - name: Verify Patroni cluster status
      shell: "patronictl -c /etc/patroni.yml list"
      register: patroni_status
      changed_when: false

    - name: Display Patroni cluster status
      debug:
        msg: "{{ patroni_status.stdout }}"
