---
- name: Configure and set up repmgr on the primary (master)
  hosts: master_nodes
  become: yes
  vars_files:
    - ../vars/repmgr.yml
    
  tasks:
    - name: Create repmgr database
      community.postgresql.postgresql_db:
        name: "{{ repmgr_db }}"
        state: present
        login_port: "{{ pg_port }}"
      become_user: postgres

    - name: Create repmgr user
      community.postgresql.postgresql_user:
        name: "{{ repmgr_user }}"
        password: "{{ repmgr_password }}"
        login_port: "{{ pg_port }}"
        db: "{{ repmgr_db }}"
        role_attr_flags: 'LOGIN,REPLICATION'
        state: present
      become_user: postgres

    - name: Create repmgr extension
      community.postgresql.postgresql_query:
        db: "{{ repmgr_db }}"
        login_port: "{{ pg_port }}"
        query: "CREATE EXTENSION IF NOT EXISTS repmgr;"
      become_user: postgres

    - name: Grant usage on the repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        objs: "repmgr"
        privs: "USAGE"
        type: schema
        roles: "{{ repmgr_user }}"
        login_port: "{{ pg_port }}"
        state: present
      become_user: postgres

    - name: Grant ALL on all tables in repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        schema: "repmgr"
        objs: "ALL_IN_SCHEMA"
        type: table
        roles: "{{ repmgr_user }}"
        privs: "ALL"
        login_port: "{{ pg_port }}"
        state: present
      become_user: postgres

    - name: Grant ALL on sequences in repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        schema: "repmgr"
        objs: "ALL_IN_SCHEMA"
        type: sequence
        roles: "{{ repmgr_user }}"
        privs: "ALL"
        login_port: "{{ pg_port }}"
        state: present
      become_user: postgres
      
    - name: Ensure PostgreSQL (master) listens on all interfaces
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?listen_addresses\s*=\s*.*'
        line: "listen_addresses = '*'"
        backup: yes
          
    - name: Restart PostgreSQL immediately
      systemd:
        name: "{{ repmgr_service_name }}"
        state: restarted

    - name: Ensure pg_hba.conf on master allows repmgr
      blockinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        insertafter: '^# IPv4 local connections:'
        block: |
          host  {{ repmgr_db }}   {{ repmgr_user }}  127.0.0.1/32  md5
          host  replication       {{ repmgr_user }}  127.0.0.1/32  md5
          host {{ repmgr_db }}    {{ repmgr_user }}  {{ master_private_ip }}/24   md5
          host replication        {{ repmgr_user }}  {{ master_private_ip }}/24   md5
          
    - name: Reload PostgreSQL
      systemd:
        name: "{{ repmgr_service_name }}"
        state: reloaded

    - name: Ensure /etc/repmgr/12 directory exists
      file:
        path: "/etc/repmgr/12"
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Place repmgr.conf on master
      template:
        src: ../templates/repmgr.conf.j2
        dest: "{{ repmgr_config_path }}"
        owner: postgres
        group: postgres
        mode: '0644'
      vars:
        node_id: "{{ repmgr_node_id }}"
        node_name: "{{ repmgr_node_name }}"
        conninfo: "host={{ master_private_ip }} dbname={{ repmgr_db }} user={{ repmgr_user }} password={{ repmgr_password }} port={{ pg_port }}"
        config_path_for_template: "{{ repmgr_config_path }}"
        service_name: "{{ repmgr_service_name }}"

    - name: Ensure PostgreSQL is started on master
      systemd:
        name: "{{ repmgr_service_name }}"
        state: started
        enabled: yes

    - name: Register master node with repmgr
      shell: >
        sudo -u postgres repmgr
        -f {{ repmgr_config_path }}
        primary register --force
      register: primary_register
      failed_when: "primary_register.rc not in [0,1]"
      changed_when: primary_register.rc == 0
