---
- name: Configure and set up repmgr on the primary (master)
  hosts: master_nodes
  become: yes
  vars_files:
    - ../vars/repmgr.yml

  pre_tasks:
    - name: Install required Python libraries (Debian/Ubuntu)
      apt:
        name: python3-psycopg2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # 1) Create the repmgr database
    - name: Create repmgr database
      community.postgresql.postgresql_db:
        name: "{{ repmgr_db }}"
        state: present
      become_user: postgres

    # 2) Create the repmgr user (with replication privileges)
    - name: Create repmgr user
      community.postgresql.postgresql_user:
        name: "{{ repmgr_user }}"
        password: "{{ repmgr_password }}"
        db: "{{ repmgr_db }}"
        role_attr_flags: 'LOGIN,REPLICATION'
        state: present
      become_user: postgres

    # 3) Create the repmgr extension in the repmgr database
    - name: Create repmgr extension
      community.postgresql.postgresql_query:
        db: "{{ repmgr_db }}"
        query: "CREATE EXTENSION IF NOT EXISTS repmgr;"
      become_user: postgres

    # 4) Grant usage on the repmgr schema (fixes permission denied for schema repmgr)
    - name: Grant usage on the repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        objs: "repmgr"         # Just the schema name
        privs: "USAGE"
        type: schema
        roles: "{{ repmgr_user }}"
        state: present
      become_user: postgres

    # 5) Grant ALL on all tables in the repmgr schema
    - name: Grant ALL on all tables in repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        schema: "repmgr"
        objs: "ALL_IN_SCHEMA"
        type: table
        roles: "{{ repmgr_user }}"
        privs: "ALL"
        state: present
      become_user: postgres

    # 6) Grant ALL on all sequences in the repmgr schema (optional but recommended)
    - name: Grant ALL on sequences in repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        schema: "repmgr"
        objs: "ALL_IN_SCHEMA"
        type: sequence
        roles: "{{ repmgr_user }}"
        privs: "ALL"
        state: present
      become_user: postgres

  tasks:
    - name: Ensure PostgreSQL (master) listens on all interfaces
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?listen_addresses\s*=\s*.*'
        line: "listen_addresses = '*'"
        backup: yes
      
    - name: Restart PostgreSQL immediately
      systemd:
        name: "{{ repmgr_service_name }}"
        state: restarted

    - name: Ensure pg_hba.conf on master allows repmgr from {{ network_subnet }}
      blockinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        insertafter: '^# IPv4 local connections:'
        block: |
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ network_subnet_master }}  md5
          host  replication       {{ repmgr_user }}  {{ network_subnet_master }}  md5
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ network_subnet_worker1 }}  md5
          host  replication       {{ repmgr_user }}  {{ network_subnet_worker1 }}  md5
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ network_subnet_worker2 }}  md5
          host  replication       {{ repmgr_user }}  {{ network_subnet_worker2 }}  md5
      notify: Reload PostgreSQL

    - name: Ensure /etc/repmgr/12 directory exists
      file:
        path: "/etc/repmgr/12"
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Place repmgr.conf on master
      template:
        src: ../templates/repmgr.conf.j2
        dest: "{{ repmgr_config_path }}"
        owner: postgres
        group: postgres
        mode: '0644'
      vars:
        node_id: "{{ repmgr_node_id }}"    # from inventory
        node_name: "{{ repmgr_node_name }}" # from inventory
        conninfo: "host={{ ansible_host }} dbname={{ repmgr_db }} user={{ repmgr_user }} password={{ repmgr_password }}"
        config_path_for_template: "{{ repmgr_config_path }}"
        service_name: "{{ repmgr_service_name }}"

    - name: Ensure PostgreSQL is started on master
      systemd:
        name: "{{ repmgr_service_name }}"
        state: started
        enabled: yes

    - name: Register master node with repmgr
      shell: >
        sudo -u postgres repmgr
        -f {{ repmgr_config_path }}
        primary register --force
      register: primary_register
      failed_when: "primary_register.rc not in [0,1]"
      changed_when: primary_register.rc == 0

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: "{{ repmgr_service_name }}"
        state: restarted

    - name: Reload PostgreSQL
      systemd:
        name: "{{ repmgr_service_name }}"
        state: reloaded