---
- name: Configure and set up repmgr on the primary (master)
  hosts: master_nodes
  become: yes
  vars_files:
    - ../vars/repmgr.yml

  pre_tasks:
    - name: Create repmgr database
      community.postgresql.postgresql_db:
        name: "{{ repmgr_db }}"
        state: present
      become_user: postgres

    - name: Create repmgr user
      community.postgresql.postgresql_user:
        name: "{{ repmgr_user }}"
        password: "{{ repmgr_password }}"
        db: "{{ repmgr_db }}"
        role_attr_flags: 'LOGIN,REPLICATION'
        state: present
      become_user: postgres

    - name: Create repmgr extension
      community.postgresql.postgresql_query:
        db: "{{ repmgr_db }}"
        query: "CREATE EXTENSION IF NOT EXISTS repmgr;"
      become_user: postgres

    - name: Grant usage on the repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        objs: "repmgr"
        privs: "USAGE"
        type: schema
        roles: "{{ repmgr_user }}"
        state: present
      become_user: postgres

    - name: Grant ALL on all tables in repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        schema: "repmgr"
        objs: "ALL_IN_SCHEMA"
        type: table
        roles: "{{ repmgr_user }}"
        privs: "ALL"
        state: present
      become_user: postgres

    - name: Grant ALL on sequences in repmgr schema
      community.postgresql.postgresql_privs:
        db: "{{ repmgr_db }}"
        schema: "repmgr"
        objs: "ALL_IN_SCHEMA"
        type: sequence
        roles: "{{ repmgr_user }}"
        privs: "ALL"
        state: present
      become_user: postgres

  tasks:
    - name: Ensure PostgreSQL (master) listens on all interfaces
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?listen_addresses\s*=\s*.*'
        line: "listen_addresses = '*'"
        backup: yes

    - name: Set PostgreSQL port to 6588
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?port\s*=\s*.*'
        line: "port = 6588"
        backup: yes

    - name: Ensure Unix socket is correctly set
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?unix_socket_directories\s*='
        line: "unix_socket_directories = '/var/run/postgresql'"
        backup: yes

    - name: Ensure pglogical is in shared_preload_libraries
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#?shared_preload_libraries\s*='
        line: "shared_preload_libraries = 'pglogical'"
        backup: yes

    - name: Configure PostgreSQL settings for pglogical
      blockinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        block: |
          wal_level = 'logical'
          max_replication_slots = 10
          max_wal_senders = 10
          track_commit_timestamp = on
          
    - name: Restart PostgreSQL to apply configuration changes
      systemd:
        name: "{{ repmgr_service_name }}"
        state: restarted

    - name: Ensure pg_hba.conf on master allows repmgr and new port
      blockinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        insertafter: '^# IPv4 local connections:'
        block: |
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ network_subnet_master }}  md5
          host  replication       {{ repmgr_user }}  {{ network_subnet_master }}  md5
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ network_subnet_worker1 }}  md5
          host  replication       {{ repmgr_user }}  {{ network_subnet_worker1 }}  md5
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ network_subnet_worker2 }}  md5
          host  replication       {{ repmgr_user }}  {{ network_subnet_worker2 }}  md5
          host  {{ repmgr_db }}   {{ repmgr_user }}  127.0.0.1/32  md5
          host  replication       {{ repmgr_user }}  127.0.0.1/32  md5
          host  {{ repmgr_db }}   {{ repmgr_user }}  {{ master_private_ip }}/24   md5
          host  replication       {{ repmgr_user }}  {{ master_private_ip }}/24   md5
          host    replication     pglogical_user    0.0.0.0/0     md5
          host    all             pglogical_user    0.0.0.0/0     md5
    - name: Reload PostgreSQL
      systemd:
        name: "{{ repmgr_service_name }}"
        state: reloaded

    - name: Ensure /etc/repmgr/12 directory exists
      file:
        path: "/etc/repmgr/12"
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Place repmgr.conf on master
      template:
        src: ../templates/repmgr.conf.j2
        dest: "{{ repmgr_config_path }}"
        owner: postgres
        group: postgres
        mode: '0644'
      vars:
        node_id: "{{ repmgr_node_id }}"
        node_name: "{{ repmgr_node_name }}"
        conninfo: "host={{ master_private_ip }} dbname={{ repmgr_db }} user={{ repmgr_user }} password={{ repmgr_password }} port=6588"
        config_path_for_template: "{{ repmgr_config_path }}"
        service_name: "{{ repmgr_service_name }}"

    - name: Ensure PostgreSQL is started on master
      systemd:
        name: "{{ repmgr_service_name }}"
        state: started
        enabled: yes

    - name: Register master node with repmgr
      shell: >
        sudo -u postgres repmgr
        -f {{ repmgr_config_path }}
        primary register --force
      register: primary_register
      failed_when: "primary_register.rc not in [0,1]"
      changed_when: primary_register.rc == 0

    - name: Verify PostgreSQL is running on port 6588
      shell: "ss -tulnp | grep :6588"
      register: postgres_port_check

    - debug:
        msg: "PostgreSQL is now listening on port 6588: {{ postgres_port_check.stdout }}"
