---
- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Configure sysctl for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1

- name: Apply sysctl parameters
  command: sysctl --system

- name: Install prerequisites if Docker is not installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  command: >
    bash -c "curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Add user to Docker group to allow non-sudo usage
  command: usermod -aG docker {{ ansible_user_id }}

- name: Enable and start containerd
  shell: |
    systemctl enable --now containerd

- name: Download CNI plugin
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz
    dest: /tmp/cni-plugins-linux-amd64-v1.4.0.tgz

- name: Extract CNI plugin
  shell: |
    mkdir -p /opt/cni/bin
    tar Cxzvf /opt/cni/bin /tmp/cni-plugins-linux-amd64-v1.4.0.tgz

- name: Load kernel modules for Kubernetes
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Configure sysctl for Kubernetes networking
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl parameters
  command: sysctl --system

- name: Enable and start containerd
  shell: |
    systemctl enable --now containerd
    systemctl restart containerd

- name: Copy containerd configuration file from control machine
  copy:
    src: ../../templates/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
