---
- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - python3-pip
      - libpq-dev
    state: present

- name: Install Patroni via apt
  apt:
    name: patroni
    state: present