---
- name: Install prerequisites
  apt:
    name:
      - vim
      - curl
      - wget
      - gpg
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Add PostgreSQL GPG key
  ansible.builtin.command: >
    bash -c "curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc |
    gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg"
  args:
    creates: /etc/apt/trusted.gpg.d/postgresql.gpg
    
- name: Add PostgreSQL repository
  ansible.builtin.shell: |
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  args:
    creates: /etc/apt/sources.list.d/pgdg.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PostgreSQL 12 and pglogical
  apt:
    name:
      - postgresql-12
      - postgresql-12-pglogical
    state: present

- name: Change PostgreSQL port in postgresql.conf
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: '^#?port\s*=\s*.*'
    line: "port = 6588"
    backup: yes

- name: Ensure PostgreSQL service is started and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Verify PostgreSQL is running on port 6588
  shell: "ss -tulnp | grep :6588"
  register: postgres_port_check

- debug:
    msg: "PostgreSQL is now listening on port 6588: {{ postgres_port_check.stdout }}"
