---
- name: Remove any old 2ndQuadrant repo file
  file:
    path: /etc/apt/sources.list.d/2ndquadrant.list
    state: absent

- name: Add the official PGDG APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add the official PGDG repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install repmgr 12
  apt:
    name: postgresql-12-repmgr
    state: present
