- name: Vérifier que le service mongod est actif
  systemd:
    name: mongod
  register: mongod_status

- name: Afficher l'état du service mongod
  debug:
    msg: "mongod est actif: {{ mongod_status.status.ActiveState == 'active' }}"

- name: Vérifier que le port 27017 est en écoute
  shell: "ss -tuln | grep -q ':27017'"
  register: mongo_port_check
  failed_when: mongo_port_check.rc != 0
  changed_when: false

- name: Afficher le résultat du port
  debug:
    msg: "MongoDB écoute sur le port 27017"


- name: Afficher la réponse du ping
  debug:
    var: mongo_ping.stdout
